[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "siddhanth-wf-iterators"
version = "0.1.0"
authors = [{name = "Siddhanth"}]
description = "A Python package for iterators, generators, and file processing"
license = {text = "MIT"}  
dependencies = ["pytest"]
